x-variables:
    flag_initial_cluster_token: &flag_initial_cluster_token '--initial-cluster-token=someClusterToken'
    common_settings: &common_settings
        image: quay.io/coreos/etcd:v3.5.16
        entrypoint: /usr/local/bin/etcd
        networks:
            - etcd_testnet

services:
    etcd-1:
        <<: *common_settings
        container_name: etcd-1
        command:
            - '--name=etcd-1'
            - '--initial-advertise-peer-urls=http://etcd-1:2380'
            - '--listen-peer-urls=http://0.0.0.0:2380'
            - '--listen-client-urls=http://0.0.0.0:2480'
            - '--advertise-client-urls=http://etcd-1:2379'
            - '--heartbeat-interval=250'
            - '--election-timeout=1250'
            - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
            - '--initial-cluster-state=new'
            - *flag_initial_cluster_token
        volumes:
            - etcd1:/etcd_data
        ports:
            - '2480:2480'

    etcd-2:
        <<: *common_settings
        container_name: etcd-2
        command:
            - '--name=etcd-2'
            - '--initial-advertise-peer-urls=http://etcd-2:2380'
            - '--listen-peer-urls=http://0.0.0.0:2380'
            - '--listen-client-urls=http://0.0.0.0:2481'
            - '--advertise-client-urls=http://etcd-2:2379'
            - '--heartbeat-interval=250'
            - '--election-timeout=1250'
            - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
            - '--initial-cluster-state=new'
            - *flag_initial_cluster_token
        volumes:
            - etcd2:/etcd_data
        ports:
            - '2481:2481'

    etcd-3:
        <<: *common_settings
        container_name: etcd-3
        command:
            - '--name=etcd-3'
            - '--initial-advertise-peer-urls=http://etcd-3:2380'
            - '--listen-peer-urls=http://0.0.0.0:2380'
            - '--listen-client-urls=http://0.0.0.0:2482'
            - '--advertise-client-urls=http://etcd-3:2379'
            - '--heartbeat-interval=250'
            - '--election-timeout=1250'
            - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
            - '--initial-cluster-state=new'
            - *flag_initial_cluster_token
        volumes:
            - etcd3:/etcd_data
        ports:
            - '2482:2482'

    pingserver1:
        image: pingserver
        container_name: pingserver1
        build:
            context: .
            dockerfile: ping.Dockerfile
        networks:
            - etcd_testnet
        command: ["serve"]
        environment:
            - PING_DISCOVERY_ADDRESSES=etcd-1:2480,etcd-2:2481,etcd-3:2482
            - PING_LISTEN_ADDRESS=0.0.0.0:8200
            - PING_METRICS_LISTEN_ADDRESS=0.0.0.0:8300
            - PING_EXTERNAL_ADDRESS=http://localhost:8200
        ports:
            - '8200:8200'
            - '8300:8300'
    pingserver2:
        image: pingserver
        container_name: pingserver2
        build:
            context: .
            dockerfile: ping.Dockerfile
        networks:
            - etcd_testnet
        command: ["serve"]
        environment:
            - PING_DISCOVERY_ADDRESSES=etcd-1:2480,etcd-2:2481,etcd-3:2482
            - PING_LISTEN_ADDRESS=0.0.0.0:8201
            - PING_METRICS_LISTEN_ADDRESS=0.0.0.0:8301
            - PING_EXTERNAL_ADDRESS=http://localhost:8201
        ports:
            - '8201:8201'
            - '8301:8301'
    pingserver3:
        image: pingserver
        container_name: pingserver3
        build:
            context: .
            dockerfile: ping.Dockerfile
        networks:
            - etcd_testnet
        command: ["serve"]
        environment:
            - PING_DISCOVERY_ADDRESSES=etcd-1:2480,etcd-2:2481,etcd-3:2482
            - PING_LISTEN_ADDRESS=0.0.0.0:8202
            - PING_METRICS_LISTEN_ADDRESS=0.0.0.0:8302
            - PING_EXTERNAL_ADDRESS=http://localhost:8202
        ports:
            - '8202:8202'
            - '8302:8302'
        

volumes:
    etcd1:
    etcd2:
    etcd3:

networks:
    etcd_testnet:
        driver: bridge
