services:
  memcached_proxy:
    image: dormando/memcached:next-proxy
    container_name: memcached_proxy
    command: memcached -l localhost -p 5001 -t 8
    cpuset: "20-23,44-47"
    volumes:
      - ./configs/1.lua:/config/config.lua
    network_mode: host
  # Memcached instances
  memcached1:
    image: memcached:latest
    container_name: memcached1
    command: memcached -m 8192 -c 10000 -t 8 -l localhost -p 11211
    cpuset: "0-3,24-27"
    network_mode: host

  memcached2:
    image: memcached:latest
    container_name: memcached2
    command: memcached -m 8192 -c 10000 -t 8 -l localhost -p 11212
    cpuset: "4-7,28-31"
    network_mode: host

  memcached3:
    image: memcached:latest
    container_name: memcached3
    command: memcached -m 8192 -c 10000 -t 8 -l localhost -p 11213
    cpuset: "8-11,32-35"
    network_mode: host

  memcached4:
    image: memcached:latest
    container_name: memcached4
    command: memcached -m 8192 -c 10000 -t 8 -l localhost -p 11214
    cpuset: "12-15,36-39"
    network_mode: host

  memcached5:
    image: memcached:latest
    container_name: memcached5
    command: memcached -m 8192 -c 10000 -t 8 -l localhost -p 11215
    cpuset: "16-19,40-43"
    network_mode: host

  # Grafana Agent for Memcached metrics
  grafana-agent:
    image: grafana/agent:latest
    container_name: grafana-agent
    environment:
      - AGENT_MODE=flow
    network_mode: host
    volumes:
      - ./grafana-agent-config.river:/etc/agent/agent-config.river
    command: run --server.http.listen-addr=0.0.0.0:12348 /etc/agent/agent-config.river

networks:
  memcached_testnet:
    driver: bridge
